import = [ "~/.config/alacritty/themes/themes/enfocado_dark.toml" ]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4
opacity = 0.95

startup_mode = "Maximized"
decorations = "None"

[font]

normal.family = "Hack Nerd Font"


